[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
solc = '0.7.6'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

fs_permissions = [{ access = "write", path = "./"}]